### ISSUE TITLE
Drop support for presets

### ISSUE THREAD

**Issue by benedfit** [mrmlnc/vscode-puglint#2]
Hi

With https://github.com/pugjs/pug-lint/issues/79, I'm going to be dropping support for presets in favour of extending config from external resources, so just wanted to let you know as I see you are using one in some of your tests

**Comment by benedfit** [comment]
v2.2.0 has been released. Details of preset deprecation can ve found at https://github.com/pugjs/pug-lint#preset-deprecated

**Comment by mrmlnc** [comment]
Thanks for the notice :+1:

**Comment by mrmlnc** [comment]
Extends now work. Just use v2.0.0 (#3).
