### ISSUE TITLE
Cannot find module pug-lint-config-build/.pug-lintrc

### ISSUE THREAD

**Issue by DevNebulae** [mrmlnc/vscode-puglint#36]
When adding the plugin to VSCode, the first thing I get is the following error message

```
Cannot find module "pug-lint-config-build/.pug-lintrc" to extend
```

What does it mean and are there any fixes for this?

**Comment by DevNebulae** [comment]
Found the issue due to not reading the documentation too carefully. It is due to `pug-lint` not being installed in the global scope. This issue may be closed now.

**Comment by mrmlnc** [comment]
Hello, @DevNebulae,

Sorry for delay. Yes, `pug-lint` must be installed globally or locally.

I close this issue, but if you have any problems, then I'll be happy to reopen it.
