### ISSUE TITLE
Should look for rule set up the directory tree

### ISSUE THREAD

**Issue by jdforsythe** [mrmlnc/vscode-puglint#4]
In my project I have server and client code in separate sub-directories of my project directory. If I put the .pug-lintrc file in the project root, the plugin sees it and works properly. If I put the .pug-lintrc file in the client directory (since it's client-specific) the plugin does not see the file, even if the .pug file is in a child directory of where the rule set is.  It should climb up the directory tree from the file until it finds a rule set.

**Comment by mrmlnc** [comment]
Thanks for the question. I will try to do this on the weekend.

**Comment by mrmlnc** [comment]
Please upgrade to version 2.1.0 and test this functionality. If there are problems, please write in this question.
